services:
  backend:
    build:
      context: .
      dockerfile: front/Dockerfile
    image: demos/login-cert/back
    ports:
      - "4430-4432:4430-4432"
    volumes:
      - ./certs:/app/certs:ro
    env_file:
      - .env
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: .
      dockerfile: back/Dockerfile
    image: demos/login-cert/front
    ports:
      - "3050:3050"
    environment:
      NODE_ENV: production
