version: "3.9"

services:
  backend:
    build: ./back
    container_name: login-cert-back
    expose:
      - "4000"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:4000/api/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  frontend:
    build: ./front
    container_name: login-cert-front
    expose:
      - "3000"
    healthcheck:
      # Next a veces responde 308; --spider lo cuenta como OK
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3000/login_cert || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  nginx:
    build: ./nginx
    container_name: login-cert-nginx
    ports:
      - "80:80"        # El ALB apunta aquí
      # - "443:443"    # (Opcional si algún día terminas TLS en NGINX)
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped
